swagger: '2.0'
info:
  $ref: info/index.yaml
#securityDefinitions:
#  UserSecurity:
#    type: apiKey
#    in: header
#    name: Authorization
#    scopes:
#      admin: Admin scope
#      user: User scope
#      media: Media scope
#security:
#  - UserSecurity: []
schemes:
  - https
basePath: '/api'
produces:
  - application/json
paths:
  $ref: paths/index.yaml
definitions:
  $ref: definitions/index.yaml
